CREATE TABLE EMPLOYEE(
EMP_ID SERIAL PRIMARY KEY,
EMP_NAME VARCHAR(20) NOT NULL,
EMP_AGE INT NOT NULL,
EMP_DEPARTMENT TEXT NOT NULL,
EMP_SALARY INTEGER NOT NULL
);

SELECT * FROM EMPLOYEE

INSERT INTO EMPLOYEE (EMP_NAME,EMP_AGE,EMP_DEPARTMENT,EMP_SALARY) VALUES 
('SAKTHI',23,'DEVELOPER',15000),
('SURESH',21,'AC MECHANIC',20000),
('SURYA',22,'SALES',10000)
DROP TABLE EMPLOYEE
BEGIN
UPDATE EMPLOYEE SET EMP_SALARY=EMP_SALARY+5000 WHERE EMP_ID=3;
SAVEPOINT SP1;

COMMIT;
ROLLBACK;

UPDATE EMPLOYEE SET EMP_SALARY=EMP_SALARY+5000 WHERE EMP_ID=2;
ROLLBACK TO SAVEPOINT SP1;

CREATE VIEW EMPLOYEE_VIEW AS SELECT EMP_NAME FROM EMPLOYEE;
SELECT * FROM EMPLOYEE_VIEW WHERE EMP_NAME='SAKTHI';

-----------------------------------------------------------------
DO
$$
DECLARE 
CHOICE INT :=1;
BEGIN
WHILE CHOICE <> 5 LOOP
RAISE NOTICE '1.CREATE VIEW';
RAISE NOTICE '2.UPDATE VIEW';
RAISE NOTICE '3.DISPLAY VIEW';

RAISE NOTICE '4.DROP VIEW';
RAISE NOTICE '5.EXIT';

CHOICE:=1;
IF CHOICE=1 THEN
CREATE OR REPLACE VIEW EMP_VIEW AS SELECT EMP_ID,EMP_NAME,EMP_SALARY  FROM EMPLOYEE;
RAISE NOTICE 'VIEW CREATED';

ELSIF CHOICE=2 THEN
UPDATE EMPLOYEE SET EMP_SALARY=EMP_SALARY+2000 WHERE EMP_ID=1;
RAISE NOTICE 'UPDATED VIEW';

ELSIF CHOICE=3 THEN
RAISE NOTICE 'USE: SELECT *FROM EMPLOYEE;';

ELSIF CHOICE=4 THEN
DROP VIEW IF EXISTS EMP_VIEW;
RAISE NOTICE 'DROP TABLE';

ELSIF CHOICE=5 THEN
RAISE NOTICE 'EXIT';

END IF;
EXIT;
END LOOP;
END $$;

SELECT * FROM EMP_VIEW;

------------------------------------------------------------------
CREATE TABLE VEHICLES_DETAIL(vehicle_id SERIAL PRIMARY KEY,
vehicle_name VARCHAR(30),
vehicle_number VARCHAR(20) NOT NULL,
capacity INT NOT NULL);

INSERT INTO VEHICLES_DETAIL 
(vehicle_name,vehicle_number,capacity) VALUES 
('BIKE','TN15 SA1234',3 ),
('VAN','TN15 SA1235',6 ),
('CAR','TN15 SA1236',20 )

CREATE TABLE DELIVERY_DETAILS
( delivery_id SERIAL PRIMARY KEY, product_name VARCHAR(20) NOT NULL,
shop_name VARCHAR(20) NOT NULL, delivery_area VARCHAR(20) NOT NULL,
status VARCHAR(20) NOT NULL);

CREATE VIEW completed_deliveries AS
SELECT *
FROM DELIVERY_DETAILS
WHERE status = 'Completed';

SELECT * FROM completed_deliveries;

CREATE INDEX idx_delivery_area
ON DELIVERY_DETAILS(delivery_area);

BEGIN;

INSERT INTO delivery_details VALUES
(1, 'Rice Bag', 'ABC Shop', 'Madurai', 'Completed');

INSERT INTO delivery_details VALUES
(2, 'Oil Can', 'XYZ Store', 'Chennai', 'Pending');

INSERT INTO delivery_details VALUES
(3, 'Sugar', 'Fresh Mart', 'Trichy', 'Completed');

COMMIT;

SELECT * FROM delivery_details;

BEGIN;

DELETE FROM delivery_details
WHERE delivery_id = 2;

SELECT * FROM delivery_details;

ROLLBACK;

SELECT * FROM delivery_details;

CREATE USER transport_user WITH PASSWORD '12345';

GRANT SELECT
ON delivery_details
TO transport_user;

SELECT * FROM transport_user;
